name: lint

on:
  push:
    branches:
      - main
      - experimental

  pull_request:
    branches:
      - main
      - experimental

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-testing.txt
      - name: flake8
          run: |
            flake8 --version
            flake8 --count --show-source --statistics smol
            # exit-zero treats all errors as warnings.
            flake8 --count --exit-zero --max-complexity=20 --statistics smol
      - name: pylint
          run: |
            pylint pymatgen
      - name: pydocstyle
          run: |
            pydocstyle --count pymatgen
