name: lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[dev]
      - name: flake8
        run: |
          flake8 --version
          flake8 --count --show-source --statistics --extend-ignore E203,E501 --max-line-length 88 smol
          # exit-zero treats all errors as warnings.
          flake8 --count --exit-zero --max-complexity=20 --statistics --extend-ignore E203,E501 --max-line-length 88 smol
      - name: black
        run: |
          black --version
          black --check --diff --color smol
      - name: pydocstyle
        run: |
          pydocstyle --version
          pydocstyle --count smol
      # Not in shape for this yet
      # - name: pylint
      #  run: |
      #     pylint smol
      #- name: mypy
       #   run: |
        #    mypy --version
         #   rm -rf .mypy_cache
          #  mypy smol
